name: 05-NodeJS-CI

on:
  push:
    branches:
      - main

jobs:
  node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up of Node
        uses: actions/setup-node@v4

      - name: Creating a packae.json
        runs: npm init -y

        with:
          node-version: 18
      - run: npm install
      - run: npm test 
